ARG baseImage=airseeker:latest

FROM ${baseImage}

LABEL airseeker_image=${baseImage} \
      config_sha256=${configHash}

ARG configFile=./config/airseeker.json

COPY ${configFile} /app/config/airseeker.json

RUN chown -R airseeker /app/config

RUN chmod +r /app/config/airseeker.json