name: Continuous Build

on:
  push:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  TARGET_NODE_VERSION: '14.17.1'

jobs:
  documentation:
    name: Check documentation
    runs-on: ubuntu-latest
    # Don't run twice for a push within an internal PR
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Clone Airseeker
        uses: actions/checkout@v2
      - name: Check hyperlinks
        # TODO: change back to v1 link checker once the bug is fixed
        # https://github.com/gaurav-nelson/github-action-markdown-link-check/pull/129
        # uses: gaurav-nelson/github-action-markdown-link-check@v1
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          config-file: .github/workflows/mlc_config.json

  lint-build-test:
    name: Lint, build, test
    runs-on: ubuntu-latest
    # Don't run twice for a push within an internal PR
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Clone Airseeker
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Compile
        run: yarn build
      - name: Run testing services
        run: yarn dev:testing-services:start
      - name: Test
        run: yarn test
      - name: Test E2E
        run: yarn test:e2e

  docker-build:
    name: Build docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Clone Airseeker
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}
          cache: yarn
      - name: Build Docker image
        run: |
          docker build -t api3/airseeker-dev:${{ github.sha }} -f docker/Dockerfile .
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push built image
        run: |
          docker push api3/airseeker-dev:${{ github.sha }}

  required-checks-passed:
    name: All required checks passed
    runs-on: ubuntu-latest
    needs: [documentation, lint-build-test, docker-build]
    steps:
      - run: exit 0
